import {
  IconBrandAndroid,
  IconBrandApple,
  IconBrandDocker,
  IconBrandFlutter,
  IconBrandGit,
  IconBrandGithub,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandLaravel,
  IconBrandNodejs,
  IconBrandPython,
  IconBrandTypescript,
  IconBrandVue,
  IconCloud,
  IconCode,
  IconDatabase,
  IconLeaf,
  IconPlug,
  IconGraph,
  IconServer,
  IconTerminal2,
} from '@tabler/icons-react';
const iconMap = {
  'brand-flutter': IconBrandFlutter,
  'brand-android': IconBrandAndroid,
  'brand-apple': IconBrandApple,
  'brand-kotlin': IconBrandKotlin,
  'brand-vue': IconBrandVue,
  'brand-nodejs': IconBrandNodejs,
  'brand-laravel': IconBrandLaravel,
  'brand-github': IconBrandGithub,
  'brand-docker': IconBrandDocker,
  'brand-python': IconBrandPython,
  'brand-javascript': IconBrandJavascript,
  'brand-typescript': IconBrandTypescript,
  'brand-git': IconBrandGit,
  code: IconCode,
  plug: IconPlug,
  schema: IconGraph,
  server: IconServer,
  database: IconDatabase,
  leaf: IconLeaf,
  flame: IconLeaf,
  cloud: IconCloud,
  waves: IconTerminal2,
  terminal: IconTerminal2,
} as const;

export function getTechnologyIcon(name: string) {
  return iconMap[name as keyof typeof iconMap] ?? IconCode;
}
